[package]
name = "advent2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcollections = "1.5.0"
intervallum = "1.4.1"
itertools = "0.12.0"
lazy_static = "1.4.0"
lcmx = "0.1.4"
regex = "1.10.2"
